# Generated by Django 3.0.3 on 2020-07-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Realtor'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
