# Generated by Django 3.0.3 on 2020-07-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200713_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
